### ISSUE TITLE
I have no idea how to build it :<

### ISSUE THREAD

**Issue by ulist** [AlexeySoshin/smali2java#7]

**Comment by ulist** [comment]
```python
root@localhost:~/smali2java# go build
smali2java.go:7:2: cannot find package "github.com/alexeysoshin/smali2java/parser" in any of:
        /usr/lib/go-1.10/src/github.com/alexeysoshin/smali2java/parser (from $GOROOT)
        /root/go/src/github.com/alexeysoshin/smali2java/parser (from $GOPATH)
```

**Comment by ulist** [comment]
```go
$ pwd ;./bin/smali2java
/data/data/com.termux/files/home/go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5584022b28]

goroutine 1 [running]:
main.parseSmaliFiles.func1(0x55840259cd, 0x13, 0x0, 0x0, 0x558409abc0, 0x40000941e0, 0x10, 0x5584081fc0)
        /data/data/com.termux/files/home/go/src/github.com/AlexeySoshin/smali2java/smali2java.go:31 +0x20
path/filepath.Walk(0x55840259cd, 0x13, 0x40000922d0, 0x0, 0x0)
        /data/data/com.termux/files/usr/lib/go/src/path/filepath/path.go:402 +0x50
main.parseSmaliFiles(0x55840259cd, 0x13)
        /data/data/com.termux/files/home/go/src/github.com/AlexeySoshin/smali2java/smali2java.go:29 +0x7c
main.main()
        /data/data/com.termux/files/home/go/src/github.com/AlexeySoshin/smali2java/smali2java.go:23 +0x78

```

**Comment by davispuh** [comment]
See my PR #8  with it you can just `go build`

**Comment by ulist** [comment]
Why I didn't notice that 😟 
Whatever thanks man @davispuh
